language: python
python:
    - '3.5'

sudo: true

matrix:
    - os: linux
      env:
      global:
          - HELLO='hello world'


script:
  - python3 -m pip install setuptools
  - python3 setup.py sdist bdist
  - python3 setup.py install
  #- srblib --help
  #- srblib --version
  - sudo add-apt-repository universe
  - sudo apt update
  - pytest

deploy:
  provider: pypi
  user: srbcheema1
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  password:
    secure: kanx8QhA8RMwe96hWEQw6MuW5c+AA1jXOgN8Rauu/4aoWuj95AlEEPJAfITlW0f8z62Qt43trQ2i/IuZITxY5O02toYfErDoZF+wQbheZJUsGIFVqCUnQnu+iGKkmpikdeJppEFCw2PXf7KJ+eKGea11ul8FEIeKqTECTD7+pPCdBEl9vBPqkIyA9GmwVQftnsFxO2H5JpH5bPMp55scL53yORjuW/PgMydFjnBxIBm/1ClXF+t/yfucoOD0xNaVaYLMHLY9AQhQGS3Gmj+itS31sKMz47lymQxWWEAjx6oX6iGPqhVzMbqn5USNX4W8xoJ6ZW9G1v6blQ5pr2VVhqxQDmrwt0XPC771ypOCbsXCKDblwkA7Ve2O/A3oHc6W8owNB+VL5GC6u8Oc+XRqE5EQXV6Ngwytwa0ZTON5OO/2Wu0G312+fi76Jm2uRQlmTayP9OFjloKXdZ8UXenFIXt6Z6Wwt5MgQukj+lPPzs9QRMtS6CeSbNyhRjCsdySieLysA3RPgybffK+2zWFItjMNaFJwKYxEXImOKxFONPZzkgr6z5XeAmICQFZ+JS3iqC1vKtITFmKh9x3dmjQX4WEEMBZqf5Gh2T/Gq4mKPLoMDKPYkb2I/TzlHsYIhucyPQdSnV3pf54WUTFgmwS5tUyEKgT1t/bbVDosrb5A0ag=
